[package]
name = "rust-chat"
version = "0.1.0"
authors = ["Dekel Yigal <dekelyi@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "*"
tokio = { version = "*", features = ["full"] }
bytes = "*"
log = "*"
pretty_env_logger = "*"
serde = { version = "*", features = ["derive"] }
rmp-serde = "*"